my_geonode/urls.py
# -*- coding: utf-8 -*-
#########################################################################
#
# Copyright (C) 2017 OSGeo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
#########################################################################

from django.conf.urls import url, include
from django.views.generic import TemplateView

from geonode.urls import urlpatterns

urlpatterns += [
## include your urls here


]

urlpatterns = [
   url(r'^/?$',
       TemplateView.as_view(template_name='site_index.html'),
       name='home'),
       
 ] + urlpatterns

my_geonode/wfpdocs/urls.py
from django.conf.urls.defaults import patterns, url, include

from tastypie.api import Api

from api import WFPDocumentResource, DocumentResource, CategoryResource

#doc_resource = WFPDocumentResource()

v1_api = Api(api_name='v1')
v1_api.register(WFPDocumentResource())
v1_api.register(DocumentResource())
v1_api.register(CategoryResource())

urlpatterns = patterns('wfp.wfpdocs.views',
    url(r'^$', 'document_browse', name='wfpdocs-browse'),
    url(r'^(?P<docid>\d+)/?$', 'document_detail', name='wfpdocs-detail'),
    url(r'^upload/?$', 'document_update', name='wfpdocs-upload'),
    url(r'^(?P<id>\d+)/update$', 'document_update', name='wfpdocs-update'),
    url(r'^api/', include(v1_api.urls)),
)

my_geonode/wfpdocs/models.py
from django.db import models
from geonode.documents.models import Document

class Category(models.Model):
    """
    A WFM Map Document category
    """
    
    name = models.CharField(max_length=255)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
        
class WFPDocument(models.Model):
    """
    A WFP document
    """
    
    ORIENTATION_CHOICES = (
        (0, 'Landscape'),
        (1, 'Portrait'),
    )
    
    FORMAT_CHOICES = (
        (0, 'A0'),
        (1, 'A1'),
        (0, 'A2'),
        (1, 'A3'),
        (0, 'A4'),
    )

    source = models.CharField(max_length=255)
    orientation = models.IntegerField('Orientation', choices=ORIENTATION_CHOICES)
    page_format = models.IntegerField('Format', choices=FORMAT_CHOICES)
    document = models.OneToOneField(Document)
    categories = models.ManyToManyField(Category, verbose_name='categories', blank=True)
    last_version = models.BooleanField(default=False)

    def __str__(self):  
          return "%s" % self.source
          
    def get_regions(self):
        regions = []
        for region in self.document.regions.all():
            regions.append(region.name)
        return ", ".join(regions )
    get_regions.short_description = 'Regions'
    
    def get_date(self):
        return self.document.date.isoformat()
    get_date.short_description = 'Date'
    
    def get_categories(self):
        categories = []
        for category in self.categories.all():
            categories.append(category.name)
        return ", ".join(categories)
    get_categories.short_description = 'Categories'
    
    def get_date_type(self):
        return self.document.date_type
    get_date_type.short_description = 'Date Type'

my_geonode/wfpdocs/forms.py
from django import forms
from models import WFPDocument, Category
from geonode.base.models import Region
from geonode.documents.forms import DocumentForm
import datetime

class WFPDocumentForm(forms.ModelForm):
    publication_date = forms.DateField(initial=datetime.date.today)
    source = forms.CharField()
    orientation = forms.ChoiceField(WFPDocument.ORIENTATION_CHOICES)
    page_format = forms.ChoiceField(WFPDocument.FORMAT_CHOICES)
    categories = forms.ModelMultipleChoiceField(Category.objects.all())
    regions = forms.ModelMultipleChoiceField(Region.objects.all(), required=False)
    last_version = forms.BooleanField(initial=True, required=False)
    
    class Meta:
        model = WFPDocument
        exclude = ('document',)
        
    def __init__(self, *args, **kwargs):
        super(WFPDocumentForm, self).__init__(*args, **kwargs)
        if hasattr(self, 'instance'):
            if hasattr(self.instance, 'document'):
                self.fields['publication_date'].initial = self.instance.document.date

my_geonode/wfpdocs/views.py
import json, os
from django.contrib.auth.decorators import login_required
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext
from django.conf import settings
from geonode.documents.models import Document
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from models import WFPDocument, Category
from forms import WFPDocumentForm
from geonode.documents.forms import DocumentForm
from geonode.people.forms import ProfileForm
from geonode.maps.views import _perms_info
from geonode.documents.views import DOCUMENT_LEV_NAMES, IMGTYPES

ALLOWED_DOC_TYPES = settings.ALLOWED_DOCUMENT_TYPES

def document_browse(request, template='wfpdocs/document_list.html'):
    from geonode.search.views import search_page
    post = request.POST.copy()
    post.update({'type': 'document'})
    request.POST = post
    return search_page(request, template=template)

def document_detail(request, docid):
    """
    The view that show details of each document
    """
    document = get_object_or_404(Document, pk=docid)
    if not request.user.has_perm('documents.view_document', obj=document):
        return HttpResponse(loader.render_to_string('401.html',
            RequestContext(request, {'error_message':
                _("You are not allowed to view this document.")})), status=403)
    try:
        related = document.content_type.get_object_for_this_type(id=document.object_id)
    except:
        related = ''

    document.popular_count += 1
    document.save()

    return render_to_response("wfpdocs/document_detail.html", RequestContext(request, {
        'permissions_json': json.dumps(_perms_info(document, DOCUMENT_LEV_NAMES)),
        'document': document,
        'imgtypes': IMGTYPES,
        'related': related
    }))
    
@login_required
def document_update(request, id=None, template_name='wfpdocs/document_form.html'):
    
    wfpdoc = None
    if id:
        wfpdoc = get_object_or_404(WFPDocument, pk=id)

    if request.method == 'POST':
        try:
            content_type = ContentType.objects.get(name=request.POST['type'])
            object_id = request.POST['q']
        except:
            content_type = None
            object_id = None
        title = request.POST['title']
        doc_file = None
        if 'file' in request.FILES:
            doc_file = request.FILES['file']
        
            if len(request.POST['title'])==0:
                return HttpResponse(_('You need to provide a document title.'))
            if not os.path.splitext(doc_file.name)[1].lower()[1:] in ALLOWED_DOC_TYPES:
                return HttpResponse(_('This file type is not allowed.'))
            if not doc_file.size < settings.MAX_DOCUMENT_SIZE * 1024 * 1024:
                return HttpResponse(_('This file is too big.'))
        # map document
        form = WFPDocumentForm(request.POST)
        if form.is_valid():
            source = form.cleaned_data.get('source')
            publication_date = form.cleaned_data.get('publication_date')
            orientation = form.cleaned_data.get('orientation')
            page_format = form.cleaned_data.get('page_format')
            categories = form.cleaned_data.get('categories')
            regions = form.cleaned_data.get('regions')
            last_version = form.cleaned_data.get('last_version')
        if wfpdoc is None:
            wfpdoc = WFPDocument()
        wfpdoc.source = source
        wfpdoc.orientation = orientation
        wfpdoc.page_format = page_format
        wfpdoc.last_version = last_version
        # if we are creating the static map, we need to create the document as well
        if not id:
            document = Document(content_type=content_type, object_id=object_id, 
                title=title, doc_file=doc_file)
            document.owner = request.user
            document.save()
            wfpdoc.document = document
        else:
            document = wfpdoc.document
        # title=title, doc_file=doc_file, date=publication_date, regions=regions
        document.owner = request.user
        document.title = title
        if doc_file:
            document.doc_file = doc_file
        document.date = publication_date
        document.regions = regions
        document.save()
        document.update_thumbnail()
        #wfpdoc = WFPDocument(source = source, orientation=orientation,
        #    page_format=page_format, document=document)
        wfpdoc.save()
        wfpdoc.categories = categories
        return HttpResponseRedirect(reverse('wfpdocs-browse'))
    else:
        if wfpdoc:
            form = WFPDocumentForm(instance=wfpdoc, 
                initial={'regions': wfpdoc.document.regions.all()})
        else:
            form = WFPDocumentForm()
        # some field in the form must be manually populated
        return render_to_response(
            'wfpdocs/document_form.html',
            { 'form': form,
            },
            RequestContext(request)
        )
        

my_geonode/wfpdocs/templates/wfpdocs/_document_list_item.html
{% load url from future %}
{% load i18n %}
{% load agon_ratings_tags %}
{% load documents_tags %}
{% load base_tags %}

{% overall_rating document "document" as document_rating %}
{% num_ratings document as num_votes %}
<article>
  <div class="content">
    <div class="item-header">
      <a href="{% url "map_detail" document.id %}"><img class="thumb" src="{{ document.get_thumbnail_url }}" /></a>
      <h3><i class="icon-file-text-alt"></i> <a href="{% url "wfpdocs-detail" document.id %}">{{ document.title }}</a></h3>
    </div>
    <div class="details">
      <div class="meta">
        <p>Doc {% trans 'from' %}: <a href="{% url "profile_detail" document.owner.username %}">{{ document.owner }}</a>, {{ document.date|timesince }} {% trans 'ago' %}</p>
        <p>{% trans 'Published' %}: {{ document.date }}</p>
        <p>{% trans 'Print Format' %}: {{ document.wfpdocument.get_page_format_display }}</p>
        <p>{% trans 'Orientation' %}: {{ document.wfpdocument.get_orientation_display }}</p>
        <p>{% trans 'Source' %}: {{ document.wfpdocument.source }}</p>
        <p>{% trans 'Regions' %}: {{ document.wfpdocument.get_regions }}</p>
        <p>{% trans 'Categories' %}: {{ document.wfpdocument.get_categories }}</p>
        <ul class="nav stats">
          <li><a href="{% url "document_detail" document.id %}"><strong>{{ document.popular_count }}</strong> {% trans "view" %}{{ document.popular_count|pluralize }}</a></li>
          <li><a href="{% url "document_detail" document.id %}#rate"><strong><span class="overall_rating"></span></strong><span class="avg_rating" data-rating="{{ document_rating }}">{{num_votes}} {% trans "ratings" %}</span></a></li>
        </ul>
      </div>
      <div class="tools pull-right">
        <a href="{% if document.doc_file %}{{ document.doc_file.url }}{% endif %}" class="btn btn-mini btn-danger pull-right">{% trans "Download" %}</a>
      </div>
    </div>
  </div>
</article>

my_geonode/wfpdocs/templates/wfpdocs/document_base.html
{% extends "site_base.html" %}
{% load i18n %}
{% load url from future %}

{% block title %} {{ block.super }} {% endblock %}

{% block body_class %}documents{% endblock %}

{% block jumbotron %}
<header class="jumbotron">
  <div class="container">
    <div class="row">
      <h1 class="span6"><i class="icon-file-text-alt"></i>{% trans "Explore Static Maps" %}</h1>
      <a href="{% url "wfpdocs-upload" %}" class="btn btn-danger btn-large pull-right">{% trans "Upload Static Maps" %}</a>
    </div>
  </div>
</header>
{% endblock %}

{% block body_outer %}
  <!-- <div class="span12">
    <ul class="nav nav-tabs" id="subnav-tabs">
      <li><a href="{% url "documents_browse" %}" class="explore">{% trans "Explore Documents" %}</a></li>
      <li><a href="{% url "document_upload" %}" class="upload">{% trans "Upload Documents" %}</a></li>
    </ul>
  </div> -->
  {% block body %}{% endblock body %}
  {% block sidebar %}{% endblock sidebar %}
{% endblock body_outer %}

my_geonode/wfpdocs/templates/wfpdocs/document_detail.html
{% extends "documents/document_base.html" %}
{% load geonode_auth %}
{% load i18n %}
{% load dialogos_tags %}
{% load agon_ratings_tags %}
{% load bootstrap_tags %}
{% load url from future %}
{% load base_tags %}

{% block title %}{{ document.title }} — {{ block.super }}{% endblock %}

{% block head %}

{{ block.super }}
{% endblock %}


{% block body_class %}documents{% endblock %}

{% block jumbotron %}
<header class="jumbotron">
  <div class="container">
    <div class="row">
      <h1 class="span6"><i class="icon-file-text-alt"></i>{% trans "Explore Map Documents" %}</h1>
      <a href="{% url "wfpdocs-browse" %}" class="btn btn-primary pull-right">{% trans "Explore Map Documents" %}</a>
    </div>
  </div>
</header>
{% endblock %}

{% block body_outer %}
  <div class="span6">
    <h2 class="page-title">{{ document.title }}</h2>
  </div>
  <div class="span6 action-group pull-right">
	  <div class="btn-group pull-right">

      {% has_obj_perm user document "documents.change_document" as can_edit_document %}
      {% if can_edit_document %}
      <div class="btn-group">
        <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="#">{% trans "Edit Document" %}<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="{% url "wfpdocs-update" document.wfpdocument.id %}">{% trans "Edit Document" %} <i class="icon-chevron-right"></i></a></li>
          <li><a href="#modal_perms" data-toggle="modal">{% trans "Edit Permissions" %} <i class="icon-chevron-right"></i></a></li>
          <li><a href="{% url "document_replace" document.id %}">{% trans "Replace this Document" %} <i class="icon-chevron-right"></i></a></li>
          <li><a href="{% url "document_remove" document.id %}">{% trans "Remove this Document" %} <i class="icon-chevron-right"></i></a></li>
        </ul>
      </div>
    {% endif %}
    <!-- 
    <div class="btn-group">
      <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#">{% trans "Download Metadata" %}<span class="caret"></span></a>
      <ul class="dropdown-menu">
        {% for link in document.link_set.metadata %}
        <li><a href="{{ link.url }}">{{ link.name }} <i class="icon-chevron-right"></i></a></li>
        {% endfor %}
      </ul>
    </div>
    -->
    </div>
  </div>

  <div class="span8">
    {% if document.extension|lower in imgtypes %}
    <div id="embedded_map">
      <img src="{% url "document_download" document.id %}" width='100%' />
    </div>
    {% else %}
    <a href="{% url "document_download" document.id %}" target="_blank">Download the {{ document }} document</a>
    {%  endif %}
       
    <div class="map-actions">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#info" data-toggle="tab"><i class="icon-info-sign"></i> {% trans "Info" %}</a></li>
        <li><a href="#comments" data-toggle="tab"><i class="icon-comment"></i> {% trans "Comments" %}</a></li>
        <li><a href="#rate" data-toggle="tab"><i class="icon-star"></i> {% trans "Ratings" %}</a></li>
        <li><a href="#share" data-toggle="tab"><i class="icon-share"></i> {% trans "Share" %}</a></li>
      </ul>
    </div>

    <div class="tab-content">
      <!--{% include "base/resourcebase_info_panel.html" with resourcebase=document %}-->
      
      <article class="description tab-pane active" id="info">
        <ul class="unstyled wide">
      
          <li>
            <strong>{% trans "Title" %}:</strong>
            {{ document.title|truncatechars:80 }}
          </li>
          <li>
            <strong>{% trans 'Publication Date' %}:</strong>
            {{ document.date }}
          </li>
          <li>
            <strong>{% trans 'Print Format' %}:</strong>
            {{ document.wfpdocument.get_page_format_display }}
          </li>
          <li>
            <strong>{% trans 'Orientation' %}:</strong>
            {{ document.wfpdocument.get_orientation_display }}
          </li>
          <li>
            <strong>{% trans 'Source' %}:</strong>
            {{ document.wfpdocument.source }}
          </li>
          <li>
            <strong>{% trans 'Regions' %}:</strong>
            {{ document.wfpdocument.get_regions }}
          </li>
          <li>
            <strong>{% trans 'Categories' %}:</strong>
            {{ document.wfpdocument.get_categories }}
          </li>
          
        </ul>
      </article>
      
      <article id="share" class="tab-pane">
        <!-- TODO: Move this to a reusable template snippet -->
        <header>
          <h3>{% trans "Share This Document" %}</h3>
        </header>
        <g:plusone size="small" href="http://{{ request.get_host }}{{ request.get_full_path }}"></g:plusone>
        <div class="fb-like" data-href="http://{{ request.get_host }}{{ request.get_full_path }}" data-send="false" data-width="50" data-layout="button_count" data-show-faces="false"></div>
        <!-- TODO: Add more sharing options -->
      </article>
        
      <article id="comments" class="tab-pane">
        {% with document as obj %}
        {% include "_comments.html" %}
        {% endwith %}
      </article>
        
      <article id="rate" class="tab-pane">
        <!-- TODO: Move this to a reusable template snippet -->
        {% if request.user.is_authenticated %}
        <h3>{% trans "Rate this document" %}</h3>
        {% user_rating request.user document "document" as user_document_rating %}
        <div id="user_rating" class="category-layer"></div>
        {% endif %}
        <h3>{% trans 'Average Rating' %}</h3>
        {% overall_rating document "document" as document_rating %}
        {% num_ratings document as num_votes %}
        <div class="overall_rating" style="float:left" data-rating="{{ document_rating }}"></div> ({{num_votes}})
        <!-- TODO: Add display of who gave what rating based -->
      </article>
    </div>
  </div>

  <aside class="span4">
    <div class="well">
      <h4>{% trans "Resource using this document" %}</h4>
      {% if layer.maps %}
      <p>{% trans "List of resources using this document:" %}</p>
      {% endif %}
      <ul class="unstyled space">
        {% if related.title %}
        <p>{% trans "This document is related to a " %} {{ document.content_type.name }}</p>
        <a href='{{ related.get_absolute_url }}'>{{ related.title }}</a>
        {% else %}
        <p>{% trans "This document is not related to any maps or layers" %}</p>
        {% endif %}
      </ul>
    </div>

    {% has_obj_perm user document "documents.change_document_permissions" as can_change_permissions %}
    {% if can_change_permissions %}
    <div class="well">
      <h4>{% trans "Permissions" %}</h4>
      <p>{% trans "Specify which users can view or modify this map" %}</p>
      <p><a href="#modal_perms" data-toggle="modal" class="btn btn-default btn-block">{% trans "Change Document Permissions" %}</a></p>
    </div>
    {% endif %}

    <div class="well">
      <h4>{% trans "About" %}</h4>
      <p>{% trans "Document Owner" %}</p>
      {% with document.owner.profile as profile %}
        {% include "people/_profile_about_item.html" %}
      {% endwith %}
      <p>{% trans "Point of Contact" %}</p>
      {% with document.poc as profile %}
        {% include "people/_profile_about_item.html" %}
      {% endwith %}
      <p>{% trans "Metadata Author" %}</p>
      {% with document.metadata_author as profile %}
        {% include "people/_profile_about_item.html" %}
      {% endwith %}
    </div>

  </aside>
  {% include "_permissions_form.html" %}
{% endblock %}

{% block extra_script %}
{% if SOCIAL_BUTTONS %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
{% endif %}
    {% if request.user.is_authenticated %}
        {% user_rating_js request.user document "document" %}
    {% else %}
        {% overall_rating document "document" as the_doc_rating %}
    {% endif %}
    <script type="text/javascript">
    $(function() {
        $('div.overall_rating').raty({
            half: true,
            readOnly: true,
            start: $('div.overall_rating').data('rating'),
            path: "{{ STATIC_URL }}lib/img/"
            {% if not request.user.is_authenticated %},
            score: {{ the_doc_rating }}
            {% endif %}
        });
        var activeTab = $('[href=' + location.hash + ']');
        activeTab && activeTab.tab('show');
    });
        {% if SOCIAL_BUTTONS %}
        (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = 'https://apis.google.com/js/plusone.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();
        {% endif %}
    </script>
    {% include "_permissions_form_js.html" %}
{% endblock extra_script %}

my_geonode/wfpdocs/templates/wfpdocs/document_form.html
{% extends "documents/document_base.html" %}
{% load i18n %}

{% block title %} {% trans "Upload Map Document" %} - {{ block.super }} {% endblock %}

{% block body_class %}documents upload{% endblock body_class %}

{% block head %}
    {% include "geonode/ext_header.html" %}
    {% include "geonode/app_header.html" %}
    {{ block.super }}
{% endblock %}

{% block jumbotron %}
<header class="jumbotron">
  <div class="container">
    <div class="row">
      <h1 class="span6"><i class="icon-file-text-alt"></i>{% trans "Upload Map Documents" %}</h1>
      <a href="{% url "wfpdocs-browse" %}" class="btn btn-primary pull-right">{% trans "Explore Map Documents" %}</a>
    </div>
  </div>
</header>
{% endblock %}

{% block body %}
  <div class="block">
    <div class="span8">
      <!-- <h2 class="page-title">{% trans "Upload Documents" %}</h2> -->
      {% if errors %}
        <ul id="errors">
        {% for error in errors %}
          <li>{{ error }}</li>
        {% endfor %}
      </ul>
      {% endif %}
      <div>
        <form id="upload_form" method="post" enctype="multipart/form-data" action="
            {% if form.instance.pk %}
                {% url "wfpdocs-update" form.instance.pk %}
            {% else %}
                {% url "wfpdocs-upload" %}
            {% endif %}
          ">
          
          <!-- title -->
          <label for="title">{% trans "Type a title" %}</label>
          <input id="title" name="title" type="text" placeholder="Title" value='{{ form.instance.document.title }}' />
          
          <!-- doc_file -->
          <label for="doc_file">{% trans "Choose a file" %}</label><input id="doc_file" name="file" type="file" />
          
          {{ form.as_p }}
          
          <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
          <input type="hidden" name="type" id="resource_type" value="" />
          <div><input type="submit" value="Save" /></div>
        </form>
      </div>
    </div>
  </div>

{% endblock %}

my_geonode/wfpdocs/templates/wfpdocs/document_list.html
{% extends "wfpdocs/document_base.html" %}
{% load i18n %}
{% load pagination_tags %}
{% load staticfiles %}
{% load url from future %}

{% block title %} {% trans "Explore Map Documents" %} - {{ block.super }} {% endblock %}

{% block body_class %}documents documents-list explore{% endblock %}

{% block body %}
    <div class="span12">
      <h2 class="page-title">{% trans "Explore Map Documents" %}</h2>
    </div>
    <div class="span8 filter">      
      {% include "search/_sort_filters.html" %}
    </div>
    <div class="span4">
      <div class="pull-right" data-viewby="list">
        {% include "_viewby.html" %}
      </div>
    </div>
    <div class="span12">
      <div class="row" id="contain-slider">
        <div class="span4">
          <div class="selections">
            <h4>
              {% trans "Your selections" %}
              <a href="." id="clear-search" class="pull-right">{% trans "Clear all" %}</a>
            </h4>
          </div>
          <div id="slide-pane">
            <a href="#" class="toggle toggle-pane"><i class="icon-chevron-left"></i></a>
            {% with type='document' %} 
            {% include "search/_general_filters.html" %}
            {% endwith %}
          </div>
        </div>
        <div class="tab-content span8 paginate paginate-auto" id="search-content">
          {% include 'wfpdocs/search_content.html' %}
        </div>
      </div>
    </div>
{% endblock %}

{% block extra_script %}
  <script type="text/javascript">
  var default_type = 'document';
  </script>
  {% include 'search_scripts.html' %}
{% endblock extra_script %}

my_geonode/wfpdocs/templates/wfpdocs/search_content.html
{% load pagination_tags %}
{% load i18n %}
<div class="tab-pane active list paginate-contents" id="all">
  <p class="search-count">Total: {{ total }}</p>
{% if object_list|length > 0 %}
{% autopaginate object_list 4 %}
{% for object in object_list %}
  {% with object.o as document %}
    {% if document.wfpdocument %}
      {% include "wfpdocs/_document_list_item.html" %}
    {% endif %}
  {% endwith %}
{% endfor %}
{% else %}
  <p class="search-count">{% trans "No data found" %}</p>
{% endif %}
</div>
{% if object_list|length > 0 %}
  {% paginate %}
{% endif %}